# Generated by Django 5.1.7 on 2025-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_status',
            field=models.CharField(choices=[('Open Profile', 'Open Profile'), ('Private Profile', 'Private Profile')], default='Open Profile', max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
